### PR TITLE
[5] Fix high CPU usage

### LINKED ISSUE #5: Something is causing some users on Big Sur to report higher than expected CPU usage for extended periods of time.
We've had a couple support emails about this now from users running Quests on Big Sur reporting higher than expected CP usage, but so far have been unable to reproduce it.

I suspect this might have something to do with users with large numbers of issues/prs getting hung up during decoding, or something else causing requests to retry/fail to decode frequently.

### PR DESCRIPTION
**Pull request by jenncoop**
### Fixes #5 

The issue was that calling `copy()` on an NSImage was triggering the draw method, which was then calling `copy()` again and so forth, creating an infinite loop.

### Testing:

- We should make sure the tint colour is correctly reflected

### Screenshots:

Tint colour testing of the menu bar:

Screen Shot 2021-05-27 at 8 42 51 AM
Screen Shot 2021-05-27 at 8 41 53 AM

Before:

Screen Shot 2021-05-27 at 9 01 12 AM

After:

Screen Shot 2021-05-27 at 8 55 46 AM

### CODE REVIEW

**Comment by brendanlensink** [comment]
🥳 🥳 🥳 🥳 🥳 🥳

**Comment by brendanlensink** [comment]
I've been running this on Big Sur in dark mode for the morning and looked away for a minute and this happened:
Screen Shot 2021-05-31 at 9 20 12 AM

**Comment by brendanlensink** [comment]
It looks like changing your desktop color will cause some issues where the icons won't update colors properly as well 
Screen Shot 2021-05-31 at 9 22 37 AM

**Comment by jenncoop** [comment]
Did this happen when your machine auto changed from dark to light?

**Comment by brendanlensink** [comment]
No, I encountered the first issue without doing anything. I was then able to reproduce it by opening a new desktop, switching the background image to be dark, and swiping between a light and dark desktop background.

On older versions the menu bar would change color based on light/dark mode (which will need to be tested as well, but I don't have access to a pre-Big Sur machine ATM), but on Big Sur the menu bar color is dictated by the color of the desktop image behind it.

**Comment by jenncoop** [comment]
Okay, I think the issue is that the loop that was causing the high CPU usage was running constantly and thus updating the image tint colour in what seemed like an automatic way. I'll add a dark mode observer and update the images when the dark mode changes.

**Review by brendanlensink — APPROVED** [review]
Looks good to me! 🚀

**Pull request merged**
